<?php 
define('CNF_APPNAME','HRV');
define('CNF_APPDESC','Consultores');
define('CNF_COMNAME','HRV Consultores');
define('CNF_EMAIL','davidmorenoazua@gmail.com',true);
define('CNF_METAKEY','');
define('CNF_METADESC','');
define('CNF_GROUP','3');
define('CNF_ACTIVATION','auto');
define('CNF_REGIST','true');
define('CNF_FRONT','true');
define('CNF_THEME','mango');
define('CNF_MULTILANG','');
define('CNF_RECAPTCHA','true');
define('CNF_RECAPTCHA_PUBLIC','6Lc3CgATAAAAAPgCiPghxW05nTD9zkP2PAbTbJ31');
define('CNF_RECAPTCHA_PRIVATE','6Lc3CgATAAAAABGFov6XNNdaTP9xM9ctDLCaGiBw');
define('CNF_LOGINFB','');
define('CNF_LOGINFB_ID','1635706256676497');
define('CNF_LOGINFB_SECRET','cb8233e47e873040b795378048b2fa9e');
define('CNF_LOGINGG','');
define('CNF_LOGINGG_ID','559583753076-52227gi95f7ndiloavemt2ai3ef2bm6g.apps.googleusercontent.com');
define('CNF_LOGINGG_SECRET','nlsH3tidIYC3THzL6inhKy3C');
define('CNF_LOGINTW','');
define('CNF_LOGINTW_ID','fJbc2gx4tIG1ZLzNTbYAaCfpy');
define('CNF_LOGINTW_SECRET','XvTc0DF83s1rjKy7zgT0zD6ilgCOSod4DLjNubUMByU1cPsgPT');
?>